
path: "/home/paula/Documentos/PAULA/NOVENO SEMESTRE/imagenes/superresolution/"
train: dataset/19_dic_2024_test_area_3cm/dataset/images_bicubic/images
val: dataset/19_dic_2024_test_area_3cm/dataset/images_bicubic/images
nc: 1
names: ['frailejones']
